import { HomeAssistant } from "./ha/types";

const languages: Record<string, Record<string, string>> = {
    en: {
        starts_in_min: "Starts in {x} minute",
        starts_in_mins: "Starts in {x} minutes",
        starts_in_hour: "Starts in {x} hour",
        starts_in_hours: "Starts in {x} hours",
        starts_in_day: "Starts in {x} day",
        starts_in_days: "Starts in {x} days",
        starts_in_week: "Starts in {x} week",
        starts_in_weeks: "Starts in {x} weeks",
        loading: "Loading events...",
        no_events: "No active events",
        more_events: "+{x} more",
        editor_show_upcoming: "Show upcoming events",
        editor_unfold_events: "Unfold Events",
        editor_show_divider: "Show Divider",
        editor_show_weekday: "Show Weekday",
        editor_show_weekday_long: "Use long weekday (e.g. Monday)",
        editor_show_add_event: "Show 'Add Event' Button",
        add_event_title: "Add Event",
        add_event_name: "Title",
        add_event_start: "Start",
        add_event_end: "End",
        add_event_all_day: "All Day",
        add_event_location: "Location",
        add_event_description: "Description",
        add_event_calendar: "Calendar",
        add_event_save: "Save",
        add_event_cancel: "Cancel",
        popup_upcoming_events: "Upcoming events",
        editor_show_more: "Show More",
        editor_show_less: "Show Less"
    },
    de: {
        starts_in_min: "Beginnt in {x} Minute",
        starts_in_mins: "Beginnt in {x} Minuten",
        starts_in_hour: "Beginnt in {x} Stunde",
        starts_in_hours: "Beginnt in {x} Stunden",
        starts_in_day: "Beginnt in {x} Tag",
        starts_in_days: "Beginnt in {x} Tagen",
        starts_in_week: "Beginnt in {x} Woche",
        starts_in_weeks: "Beginnt in {x} Wochen",
        loading: "Lade Termine...",
        no_events: "Keine aktiven Termine",
        more_events: "+{x} weitere",
        editor_show_upcoming: "Zeige bevorstehende Ereignisse",
        editor_unfold_events: "Ereignisse ausklappen",
        editor_show_divider: "Zeige Trenner",
        editor_show_weekday: "Zeige Wochentag",
        editor_show_weekday_long: "Ausgeschrieben (z.B. Montag)",
        editor_show_add_event: "Zeige 'Neuer Termin' Button",
        add_event_title: "Neuer Termin",
        add_event_name: "Titel",
        add_event_start: "Start",
        add_event_end: "Ende",
        add_event_all_day: "Ganztägig",
        add_event_location: "Ort",
        add_event_description: "Beschreibung",
        add_event_calendar: "Kalender",
        add_event_save: "Speichern",
        add_event_cancel: "Abbrechen",
        popup_upcoming_events: "Bevorstehende Ereignisse",
        editor_show_more: "Mehr anzeigen",
        editor_show_less: "Weniger anzeigen"
    },
    fr: {
        starts_in_min: "Commence dans {x} minute",
        starts_in_mins: "Commence dans {x} minutes",
        starts_in_hour: "Commence dans {x} heure",
        starts_in_hours: "Commence dans {x} heures",
        starts_in_day: "Commence dans {x} jour",
        starts_in_days: "Commence dans {x} jours",
        starts_in_week: "Commence dans {x} semaine",
        starts_in_weeks: "Commence dans {x} semaines",
        loading: "Chargement...",
        no_events: "Aucun événement",
        more_events: "+{x} autres",
        editor_show_upcoming: "Afficher les événements à venir",
        editor_unfold_events: "Déplier les événements",
        editor_show_divider: "Afficher le séparateur",
        editor_show_weekday: "Afficher le jour de la semaine",
        editor_show_weekday_long: "Format long (ex. Lundi)",
        editor_show_add_event: "Bouton Nouveau",
        add_event_title: "Nouvel événement",
        add_event_name: "Titre",
        add_event_start: "Début",
        add_event_end: "Fin",
        add_event_all_day: "Toute la journée",
        add_event_location: "Lieu",
        add_event_description: "Description",
        add_event_calendar: "Calendrier",
        add_event_save: "Enregistrer",
        add_event_cancel: "Annuler",
        popup_upcoming_events: "Événements à venir",
        editor_show_more: "Afficher plus",
        editor_show_less: "Afficher moins"
    },
    it: {
        starts_in_min: "Inizia tra {x} minuto",
        starts_in_mins: "Inizia tra {x} minuti",
        starts_in_hour: "Inizia tra {x} ora",
        starts_in_hours: "Inizia tra {x} ore",
        starts_in_day: "Inizia tra {x} giorno",
        starts_in_days: "Inizia tra {x} giorni",
        starts_in_week: "Inizia tra {x} settimana",
        starts_in_weeks: "Inizia tra {x} settimane",
        loading: "Caricamento...",
        no_events: "Nessun evento",
        more_events: "+{x} altri",
        editor_show_upcoming: "Mostra prossimi eventi",
        editor_unfold_events: "Espandi gli eventi",
        editor_show_divider: "Mostra divisore",
        editor_show_weekday: "Mostra giorno della settimana",
        editor_show_weekday_long: "Usa nome completo (es. Lunedì)",
        editor_show_add_event: "Mostra pulsante Aggiungi",
        add_event_title: "Aggiungi Evento",
        add_event_name: "Titolo",
        add_event_start: "Inizio",
        add_event_end: "Fine",
        add_event_all_day: "Tutto il giorno",
        add_event_location: "Luogo",
        add_event_description: "Descrizione",
        add_event_calendar: "Calendario",
        add_event_save: "Salva",
        add_event_cancel: "Annulla",
        popup_upcoming_events: "Prossimi eventi",
        editor_show_more: "Mostra di più",
        editor_show_less: "Mostra meno"
    },
    es: {
        starts_in_min: "Empieza en {x} minuto",
        starts_in_mins: "Empieza en {x} minutos",
        starts_in_hour: "Empieza en {x} hora",
        starts_in_hours: "Empieza en {x} horas",
        starts_in_day: "Empieza en {x} día",
        starts_in_days: "Empieza en {x} días",
        starts_in_week: "Empieza en {x} semana",
        starts_in_weeks: "Empieza en {x} semanas",
        loading: "Cargando...",
        no_events: "No hay eventos",
        more_events: "+{x} más",
        editor_show_upcoming: "Mostrar próximos eventos",
        editor_unfold_events: "Desplegar eventos",
        editor_show_divider: "Mostrar divisor",
        editor_show_weekday: "Mostrar día de la semana",
        editor_show_weekday_long: "Formato largo (ej. Lunes)",
        editor_show_add_event: "Mostrar botón Añadir Evento",
        add_event_title: "Añadir Evento",
        add_event_name: "Título",
        add_event_start: "Inicio",
        add_event_end: "Fin",
        add_event_all_day: "Todo el día",
        add_event_location: "Ubicación",
        add_event_description: "Descripción",
        add_event_calendar: "Calendario",
        add_event_save: "Guardar",
        add_event_cancel: "Cancelar",
        popup_upcoming_events: "Próximos eventos",
        editor_show_more: "Mostrar más",
        editor_show_less: "Mostrar menos"
    },
    nl: {
        starts_in_min: "Begint over {x} minuut",
        starts_in_mins: "Begint over {x} minuten",
        starts_in_hour: "Begint over {x} uur",
        starts_in_hours: "Begint over {x} uur",
        starts_in_day: "Begint over {x} dag",
        starts_in_days: "Begint over {x} dagen",
        starts_in_week: "Begint over {x} week",
        starts_in_weeks: "Begint over {x} weken",
        loading: "Laden...",
        no_events: "Geen evenementen",
        more_events: "+{x} meer",
        editor_show_upcoming: "Toon aankomende evenementen",
        editor_unfold_events: "Evenementen uitvouwen",
        editor_show_divider: "Toon verdeler",
        editor_show_weekday: "Toon weekdag",
        editor_show_weekday_long: "Gebruik lange notatie (bijv. Maandag)",
        editor_show_add_event: "Toon Toevoegen knop",
        add_event_title: "Evenement toevoegen",
        add_event_name: "Titel",
        add_event_start: "Start",
        add_event_end: "Eind",
        add_event_all_day: "Hele dag",
        add_event_location: "Locatie",
        add_event_description: "Beschrijving",
        add_event_calendar: "Kalender",
        add_event_save: "Opslaan",
        add_event_cancel: "Annuleren",
        popup_upcoming_events: "Aankomende evenementen",
        editor_show_more: "Toon meer",
        editor_show_less: "Toon minder"
    },
    pt: {
        starts_in_min: "Começa em {x} minuto",
        starts_in_mins: "Começa em {x} minutos",
        starts_in_hour: "Começa em {x} hora",
        starts_in_hours: "Começa em {x} horas",
        starts_in_day: "Começa em {x} dia",
        starts_in_days: "Começa em {x} dias",
        starts_in_week: "Começa em {x} semana",
        starts_in_weeks: "Começa em {x} semanas",
        loading: "A carregar...",
        no_events: "Sem eventos",
        more_events: "+{x} mais",
        editor_show_upcoming: "Mostrar próximos eventos",
        editor_unfold_events: "Desdobrar eventos",
        editor_show_divider: "Mostrar divisor",
        editor_show_weekday: "Mostrar dia da semana",
        editor_show_weekday_long: "Formato longo (ex. Segunda-feira)",
        editor_show_add_event: "Mostrar botão Adicionar",
        add_event_title: "Adicionar evento",
        add_event_name: "Título",
        add_event_start: "Início",
        add_event_end: "Fim",
        add_event_all_day: "Dia inteiro",
        add_event_location: "Local",
        add_event_description: "Descrição",
        add_event_calendar: "Calendário",
        add_event_save: "Salvar",
        add_event_cancel: "Cancelar",
        popup_upcoming_events: "Próximos eventos",
        editor_show_more: "Mostrar mais",
        editor_show_less: "Mostrar menos"
    },
    ru: {
        starts_in_min: "Начнется через {x} минуту",
        starts_in_mins: "Начнется через {x} мин.",
        starts_in_hour: "Начнется через {x} час",
        starts_in_hours: "Начнется через {x} ч.",
        starts_in_day: "Начнется через {x} день",
        starts_in_days: "Начнется через {x} дн.",
        starts_in_week: "Начнется через {x} неделю",
        starts_in_weeks: "Начнется через {x} нед.",
        loading: "Загрузка...",
        no_events: "Нет событий",
        more_events: "ещё +{x}",
        editor_show_upcoming: "Показать предстоящие события",
        editor_unfold_events: "Развернуть события",
        editor_show_divider: "Показать разделитель",
        editor_show_weekday: "Показать день недели",
        editor_show_weekday_long: "Использовать полное название (напр. Понедельник)",
        editor_show_add_event: "Показать кнопку Добавить",
        add_event_title: "Добавить событие",
        add_event_name: "Название",
        add_event_start: "Начало",
        add_event_end: "Конец",
        add_event_all_day: "Весь день",
        add_event_location: "Место",
        add_event_description: "Описание",
        add_event_calendar: "Календарь",
        add_event_save: "Сохранить",
        add_event_cancel: "Отмена",
        popup_upcoming_events: "Предстоящие события",
        editor_show_more: "Показать больше",
        editor_show_less: "Показать меньше"
    },
    pl: {
        starts_in_min: "Rozpoczyna się za {x} minutę",
        starts_in_mins: "Rozpoczyna się za {x} min.",
        starts_in_hour: "Rozpoczyna się za {x} godzinę",
        starts_in_hours: "Rozpoczyna się za {x} godz.",
        starts_in_day: "Rozpoczyna się za {x} dzień",
        starts_in_days: "Rozpoczyna się za {x} dni",
        starts_in_week: "Rozpoczyna się za {x} tydzień",
        starts_in_weeks: "Rozpoczyna się za {x} tyg.",
        loading: "Ładowanie...",
        no_events: "Brak wydarzeń",
        more_events: "+{x} więcej",
        editor_show_upcoming: "Pokaż nadchodzące wydarzenia",
        editor_unfold_events: "Rozwiń wydarzenia",
        editor_show_divider: "Pokaż dzielnik",
        editor_show_weekday: "Pokaż dzień tygodnia",
        editor_show_weekday_long: "Użyj pełnej nazwy (np. Poniedziałek)",
        editor_show_add_event: "Pokaż przycisk Dodaj",
        add_event_title: "Dodaj wydarzenie",
        add_event_name: "Tytuł",
        add_event_start: "Początek",
        add_event_end: "Koniec",
        add_event_all_day: "Cały dzień",
        add_event_location: "Lokalizacja",
        add_event_description: "Opis",
        add_event_calendar: "Kalendarz",
        add_event_save: "Zapisz",
        add_event_cancel: "Anuluj",
        popup_upcoming_events: "Nadchodzące wydarzenia",
        editor_show_more: "Pokaż więcej",
        editor_show_less: "Pokaż mniej"
    },
    sv: {
        starts_in_min: "Börjar om {x} minut",
        starts_in_mins: "Börjar om {x} minuter",
        starts_in_hour: "Börjar om {x} timme",
        starts_in_hours: "Börjar om {x} timmar",
        starts_in_day: "Börjar om {x} dag",
        starts_in_days: "Börjar om {x} dagar",
        starts_in_week: "Börjar om {x} vecka",
        starts_in_weeks: "Börjar om {x} veckor",
        loading: "Laddar...",
        no_events: "Inga händelser",
        more_events: "+{x} till",
        editor_show_upcoming: "Visa kommande händelser",
        editor_unfold_events: "Fäll ut evenemang",
        editor_show_divider: "Visa avdelare",
        editor_show_weekday: "Visa veckodag",
        editor_show_weekday_long: "Använd långt format (t.ex. Måndag)",
        editor_show_add_event: "Visa Lägg till-knapp",
        add_event_title: "Lägg till händelse",
        add_event_name: "Titel",
        add_event_start: "Start",
        add_event_end: "Slut",
        add_event_all_day: "Heldag",
        add_event_location: "Plats",
        add_event_description: "Beskrivning",
        add_event_calendar: "Kalender",
        add_event_save: "Spara",
        add_event_cancel: "Avbryt",
        popup_upcoming_events: "Kommande händelser",
        editor_show_more: "Visa mer",
        editor_show_less: "Visa mindre"
    },
    da: {
        starts_in_min: "Starter om {x} minut",
        starts_in_mins: "Starter om {x} minutter",
        starts_in_hour: "Starter om {x} time",
        starts_in_hours: "Starter om {x} timer",
        starts_in_day: "Starter om {x} dag",
        starts_in_days: "Starter om {x} dage",
        starts_in_week: "Starter om {x} uge",
        starts_in_weeks: "Starter om {x} uger",
        loading: "Indlæser...",
        no_events: "Ingen begivenheder",
        more_events: "+{x} mere",
        editor_show_upcoming: "Vis kommende begivenheder",
        editor_unfold_events: "Udfold begivenheder",
        editor_show_divider: "Vis skillelinje",
        editor_show_weekday: "Vis ugedag",
        editor_show_weekday_long: "Brug langt format (f.eks. Mandag)",
        editor_show_add_event: "Vis Tilføj-knap",
        add_event_title: "Tilføj begivenhed",
        add_event_name: "Titel",
        add_event_start: "Start",
        add_event_end: "Slut",
        add_event_all_day: "Hele dagen",
        add_event_location: "Sted",
        add_event_description: "Beskrivelse",
        add_event_calendar: "Kalender",
        add_event_save: "Gem",
        add_event_cancel: "Annuller",
        popup_upcoming_events: "Kommende begivenheder",
        editor_show_more: "Vis mere",
        editor_show_less: "Vis mindre"
    },
    no: {
        starts_in_min: "Starter om {x} minutt",
        starts_in_mins: "Starter om {x} minutter",
        starts_in_hour: "Starter om {x} time",
        starts_in_hours: "Starter om {x} timer",
        starts_in_day: "Starter om {x} dag",
        starts_in_days: "Starter om {x} dager",
        starts_in_week: "Starter om {x} uke",
        starts_in_weeks: "Starter om {x} uker",
        loading: "Laster...",
        no_events: "Ingen hendelser",
        more_events: "+{x} til",
        editor_show_upcoming: "Vis kommende hendelser",
        editor_unfold_events: "Brett ut hendelser",
        editor_show_divider: "Vis skillelinje",
        editor_show_weekday: "Vis ukedag",
        editor_show_weekday_long: "Bruk langt format (f.eks. Mandag)",
        editor_show_add_event: "Vis Legg til-knapp",
        add_event_title: "Legg til hendelse",
        add_event_name: "Tittel",
        add_event_start: "Start",
        add_event_end: "Slutt",
        add_event_all_day: "Hele dagen",
        add_event_location: "Sted",
        add_event_description: "Beskrivelse",
        add_event_calendar: "Kalender",
        add_event_save: "Lagre",
        add_event_cancel: "Avbryt",
        popup_upcoming_events: "Kommende hendelser",
        editor_show_more: "Vis mer",
        editor_show_less: "Vis mindre"
    },
    fi: {
        starts_in_min: "Alkaa {x} minuutin kuluttua",
        starts_in_mins: "Alkaa {x} minuutin kuluttua",
        starts_in_hour: "Alkaa {x} tunnin kuluttua",
        starts_in_hours: "Alkaa {x} tunnin kuluttua",
        starts_in_day: "Alkaa {x} päivän kuluttua",
        starts_in_days: "Alkaa {x} päivän kuluttua",
        starts_in_week: "Alkaa {x} viikon kuluttua",
        starts_in_weeks: "Alkaa {x} viikon kuluttua",
        loading: "Ladataan...",
        no_events: "Ei tapahtumia",
        more_events: "+{x} lisää",
        editor_show_upcoming: "Näytä tulevat tapahtumat",
        editor_unfold_events: "Avaa tapahtumat",
        editor_show_divider: "Näytä jakaja",
        editor_show_weekday: "Näytä viikonpäivä",
        editor_show_weekday_long: "Käytä pitkää nimeä (esim. Maanantai)",
        editor_show_add_event: "Paina Lisää näppäintä",
        add_event_title: "Lisää tapahtuma",
        add_event_name: "Nimi",
        add_event_start: "Alku",
        add_event_end: "Loppu",
        add_event_all_day: "Koko päivä",
        add_event_location: "Sijainti",
        add_event_description: "Kuvaus",
        add_event_calendar: "Kalenteri",
        add_event_save: "Tallenna",
        add_event_cancel: "Peruuta",
        popup_upcoming_events: "Tulevat tapahtumat",
        editor_show_more: "Näytä enemmän",
        editor_show_less: "Näytä vähemmän"
    },
    cs: {
        starts_in_min: "Začíná za {x} minutu",
        starts_in_mins: "Začíná za {x} minut",
        starts_in_hour: "Začíná za {x} hodinu",
        starts_in_hours: "Začíná za {x} hodin",
        starts_in_day: "Začíná za {x} den",
        starts_in_days: "Začíná za {x} dní",
        starts_in_week: "Začíná za {x} týden",
        starts_in_weeks: "Začíná za {x} týdnů",
        loading: "Načítání...",
        no_events: "Žádné události",
        more_events: "+{x} další",
        editor_show_upcoming: "Zobrazit nadcházející události",
        editor_unfold_events: "Rozvinout události",
        editor_show_divider: "Zobrazit dělič",
        editor_show_weekday: "Zobrazit den v týdnu",
        editor_show_weekday_long: "Použít celý název (např. Pondělí)",
        editor_show_add_event: "Zobrazit tlačítko Přidat",
        add_event_title: "Přidat událost",
        add_event_name: "Název",
        add_event_start: "Začátek",
        add_event_end: "Konec",
        add_event_all_day: "Celý den",
        add_event_location: "Místo",
        add_event_description: "Popis",
        add_event_calendar: "Kalendář",
        add_event_save: "Uložit",
        add_event_cancel: "Zrušit",
        popup_upcoming_events: "Nadcházející události",
        editor_show_more: "Zobrazit více",
        editor_show_less: "Zobrazit méně"
    },
    hu: {
        starts_in_min: "Kezdés {x} perc múlva",
        starts_in_mins: "Kezdés {x} perc múlva",
        starts_in_hour: "Kezdés {x} óra múlva",
        starts_in_hours: "Kezdés {x} óra múlva",
        starts_in_day: "Kezdés {x} nap múlva",
        starts_in_days: "Kezdés {x} nap múlva",
        starts_in_week: "Kezdés {x} hét múlva",
        starts_in_weeks: "Kezdés {x} hét múlva",
        loading: "Betöltés...",
        no_events: "Nincs esemény",
        more_events: "+{x} további",
        editor_show_upcoming: "Közelgő események megjelenítése",
        editor_unfold_events: "Események kibontása",
        editor_show_divider: "Osztó megjelenítése",
        editor_show_weekday: "Hét napjának mutatása",
        editor_show_weekday_long: "Hosszú formátum (pl. Hétfő)",
        editor_show_add_event: "Hozzáadás gomb mutatása",
        add_event_title: "Esemény Hozzáadása",
        add_event_name: "Cím",
        add_event_start: "Kezdés",
        add_event_end: "Befejezés",
        add_event_all_day: "Egész napos",
        add_event_location: "Helyszín",
        add_event_description: "Leírás",
        add_event_calendar: "Naptár",
        add_event_save: "Mentés",
        add_event_cancel: "Mégse",
        popup_upcoming_events: "Közelgő események",
        editor_show_more: "Több mutatása",
        editor_show_less: "Kevesebb mutatása"
    }
};

export function localize(hass: HomeAssistant, key: string, search?: string, replace?: string): string {
    const lang = hass.locale?.language || hass.language || 'en';
    let translated: string;

    if (languages[lang] && languages[lang][key]) {
        translated = languages[lang][key];
    } else if (languages['en'] && languages['en'][key]) {
        translated = languages['en'][key];
    } else {
        return key;
    }

    if (search && replace) {
        translated = translated.replace(search, replace);
    }
    return translated;
}
